### ISSUE TITLE
Out of memory error

### ISSUE THREAD

**Issue by dergachev** [dergachev/screengif#2]
See this gist for problem description and workaround.

https://gist.github.com/dergachev/6541373

**Comment by fungku** [comment]
Is that the same as this error?

```
Processing image: 156/587/Library/Ruby/Gems/2.0.0/gems/screengif-0.0.3/lib/screengif.rb:94:in `contrast': UnableToOpenPixelCache `': Too many open files @ error/cache.c/OpenPixelCache/3711 (Magick::ImageMagickError)
	from /Library/Ruby/Gems/2.0.0/gems/screengif-0.0.3/lib/screengif.rb:94:in `block in start'
	from (eval):2:in `each'
	from (eval):2:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/screengif-0.0.3/lib/screengif.rb:83:in `each_with_index'
	from /Library/Ruby/Gems/2.0.0/gems/screengif-0.0.3/lib/screengif.rb:83:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/screengif-0.0.3/bin/screengif:10:in `<top (required)>'
	from /usr/bin/screengif:23:in `load'
	from /usr/bin/screengif:23:in `<main>'
```
