### ISSUE TITLE
"Too many open files" error when performing a simple conversion

### ISSUE THREAD

**Issue by IshmaelYavitz** [dergachev/screengif#22]
The .mov is 12.8 mb.

No fancy command-line arguments were used.

There wasn't a newline after "151/610" - I introduced it here for clarity.

````
> screengif --input screen-recording.mov --output screen-recording.gif
Processing image: 151/610
/usr/local/lib/ruby/gems/2.2.0/gems/screengif-0.0.3/lib/screengif.rb:94:in `contrast': UnableToOpenPixelCache `': Too many open files @ error/cache.c/OpenPixelCache/3720 (Magick::ImageMagickError)
	from /usr/local/lib/ruby/gems/2.2.0/gems/screengif-0.0.3/lib/screengif.rb:94:in `block in start'
	from (eval):2:in `each'
	from (eval):2:in `each'
	from /usr/local/lib/ruby/gems/2.2.0/gems/screengif-0.0.3/lib/screengif.rb:83:in `each_with_index'
	from /usr/local/lib/ruby/gems/2.2.0/gems/screengif-0.0.3/lib/screengif.rb:83:in `start'
	from /usr/local/lib/ruby/gems/2.2.0/gems/screengif-0.0.3/bin/screengif:10:in `<top (required)>'
	from /usr/local/bin/screengif:23:in `load'
	from /usr/local/bin/screengif:23:in `<main>'

>
````

**Comment by IshmaelYavitz** [comment]
I closed all non-essential programs and tried again.

It fails at the same place: image 151 of 610.

**Comment by dergachev** [comment]
Thanks for your detailed feedback, I'll look at it when I can!
Please upload input .mov file if possible.
